#! /usr/bin/env ruby

unless RUBY_VERSION >= "2.0.0"
  raise "Please upgrade to at least Ruby 2.0.0."
end

TYPES = {
  "0"                => 0,
  "2048"             => 2048,
  "42"               => 42,
  "Shift_JIS_String" => "hello haskell".force_encoding("Shift_JIS"),
  "US_ASCII_String"  => "hello haskell".force_encoding("US-ASCII"),
  "UTF_8_String"     => "hello haskell",
  "bigArray"         => (-10000..10000).to_a,
  "boolArray"        => [true, false],
  "false"            => false,
  "fixnumArray"      => [-2048, -42, 0, 42, 2048],
  "fixnumHash"       => { 0 => false, 1 => true },
  "float"            => 3.33333,
  "neg2048"          => -2048,
  "neg42"            => -42,
  "nil"              => nil,
  "nilArray"         => [nil],
  "railsCookie"      => { "session_id" => "ba0844151d",
                          "_csrf_token" => "a9212445c5",
                          "user_id" => "1" },
  "stringArray"      => ["hello", "haskell", "hello", "haskell"],
  "symbol"           => :hello_haskell,
  "symbolArray"      => [:hello, :haskell, :hello, :haskell],
  "true"             => true
}

def dump(name, x)
  File.open([File.expand_path(File.dirname(__FILE__)), "bin", [name, "bin"].join(".")].join("/"), "w") do |f|
    f.write(Marshal.dump(x))
  end
end

puts "Dumping binary representations..."

TYPES.each do |key, val|
  dump(key, val)
end
